apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Aligné avec Terraform (environments/dev) : namespace locatic-staging.
# En prod, Ansible/Kustomize peut remplacer par locatic-prod.
namespace: locatic-staging

resources:
  - app.yaml
  - configmap.yaml
  - nginx.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: locatic
    includeSelectors: true
