apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: locatic-sqlite-data
  namespace: locatic
  labels:
    app.kubernetes.io/name: locatic
    app.kubernetes.io/component: sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
