apiVersion: v1
kind: ConfigMap
metadata:
  name: locatic-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: locatic
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- toYaml .Values.config | nindent 2 }}