{{- if .Values.sqlite.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sqlite.pvc.name | default "locatic-sqlite" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: locatic
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    {{- toYaml .Values.sqlite.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.sqlite.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.sqlite.pvc.size }}
{{- end }}