apiVersion: v1
kind: Secret
metadata:
  name: locatic-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: locatic
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
{{- with .Values.secrets }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}