apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: locatic-prod

labels:
  - pairs:
      app.kubernetes.io/environment: prod
      managed-by: kustomize
    includeSelectors: false

resources:
  - ../../base
