apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: locatic-staging

labels:
  - pairs:
      app.kubernetes.io/environment: staging
      managed-by: kustomize
    includeSelectors: false

resources:
  - ../../base
