apiVersion: v1
kind: Service
metadata:
  name: locatic
  labels:
    {{- include "locatic.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    {{- include "locatic.selectorApp" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
