{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: locatic-nginx
  labels:
    {{- include "locatic.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.serviceType }}
  selector:
    {{- include "locatic.selectorNginx" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.nginx.httpPort }}
      targetPort: http
    - name: metrics
      port: {{ .Values.nginx.metricsPort }}
      targetPort: metrics
{{- end }}
